# Generated by Django 3.2.3 on 2021-07-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users profile'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Users image'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(),
        ),
    ]
