# Generated by Django 3.2.3 on 2021-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210716_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='/media/logo/default.jpg'),
        ),
    ]
