# Generated by Django 3.2.3 on 2021-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0063_auto_20210717_1646'),
        ('accounts', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, to='channel.channel'),
        ),
    ]
