# Generated by Django 3.2.3 on 2021-07-25 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
