# Generated by Django 3.2.6 on 2021-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210728_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='User email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default=1, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='User phone'),
        ),
    ]
