# Generated by Django 3.2.2 on 2021-06-13 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField(max_length=50)),
                ('logo', models.ImageField(upload_to='pics')),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('about_allah', models.TextField()),
                ('fb_link', models.TextField()),
                ('twitter_link', models.TextField()),
                ('web_link', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('playlist', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
    ]
