# Generated by Django 3.2.2 on 2021-06-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
