# Generated by Django 3.2.2 on 2021-06-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_rename_owner_channel_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
