# Generated by Django 3.2.2 on 2021-06-14 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_rename_owner_id_channel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 14, 15, 53, 13, 824151)),
        ),
    ]
