# Generated by Django 3.2.2 on 2021-06-16 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20210614_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 16, 10, 48, 58, 106124)),
        ),
    ]
