# Generated by Django 3.2.2 on 2021-06-22 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210616_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 22, 15, 26, 14, 144336)),
        ),
    ]
