# Generated by Django 3.2.2 on 2021-06-22 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='thumbnail/image.jpg', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 22, 15, 37, 2, 651384)),
        ),
    ]
