# Generated by Django 3.2.2 on 2021-06-24 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_auto_20210624_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 24, 7, 54, 32, 480196)),
        ),
        migrations.DeleteModel(
            name='folder',
        ),
    ]
