# Generated by Django 3.2.2 on 2021-06-24 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_auto_20210624_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 24, 8, 12, 24, 850829)),
        ),
    ]
