# Generated by Django 3.2.3 on 2021-06-30 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_auto_20210630_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 30, 8, 56, 58, 483474)),
        ),
    ]
