# Generated by Django 3.2.3 on 2021-07-02 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0017_auto_20210630_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 2, 8, 34, 37, 288768)),
        ),
    ]
