# Generated by Django 3.2.3 on 2021-07-03 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0021_alter_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 3, 15, 26, 2, 779828)),
        ),
    ]
