# Generated by Django 3.2.3 on 2021-07-03 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0024_auto_20210704_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 4, 5, 17, 12, 818010)),
        ),
    ]
