# Generated by Django 3.2.3 on 2021-07-04 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0025_alter_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 4, 6, 14, 2, 792496)),
        ),
    ]
