# Generated by Django 3.2.3 on 2021-07-14 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0030_alter_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 14, 18, 9, 18, 759759)),
        ),
    ]
