# Generated by Django 3.2.3 on 2021-07-14 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0031_auto_20210714_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 14, 18, 25, 12, 947650)),
        ),
    ]
