# Generated by Django 3.2.3 on 2021-07-15 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0033_alter_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 16, 54, 4, 911424)),
        ),
    ]
