# Generated by Django 3.2.3 on 2021-07-15 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0034_auto_20210715_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 15, 21, 12, 52, 488504)),
        ),
    ]
