# Generated by Django 3.2.3 on 2021-07-16 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0037_auto_20210716_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 4, 42, 15, 402049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 16, 10, 42, 15, 403050)),
        ),
    ]
