# Generated by Django 3.2.3 on 2021-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0041_video_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.TextField(default='Public'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(default='/media/thumbnail/image.jpg'),
        ),
    ]
