# Generated by Django 3.2.3 on 2021-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0042_auto_20210717_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=100),
        ),
    ]
