# Generated by Django 3.2.3 on 2021-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0043_alter_video_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=100),
        ),
    ]
