# Generated by Django 3.2.3 on 2021-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0044_alter_video_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default='/media/thumbnail/image.jpg'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
