# Generated by Django 3.2.3 on 2021-07-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0045_auto_20210717_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='playlist',
            new_name='folder',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time',
        ),
    ]
