# Generated by Django 3.2.3 on 2021-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0049_auto_20210717_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='videofile',
        ),
    ]
