# Generated by Django 3.2.3 on 2021-07-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0050_auto_20210717_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TextField()),
                ('title', models.TextField()),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.video')),
            ],
        ),
    ]
