# Generated by Django 3.2.3 on 2021-07-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0051_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duration',
        ),
    ]
