# Generated by Django 3.2.3 on 2021-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0052_delete_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
