# Generated by Django 3.2.3 on 2021-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0058_alter_video_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.TextField(null=True),
        ),
    ]
