# Generated by Django 3.2.3 on 2021-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0061_auto_20210717_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='/media/thumbnail/image.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
