# Generated by Django 3.2.3 on 2021-07-18 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0063_auto_20210717_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unlikes',
            field=models.ManyToManyField(blank=True, default=None, related_name='Unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
