# Generated by Django 3.2.3 on 2021-07-18 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0064_video_unlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='follower',
            field=models.ManyToManyField(blank=True, default=None, related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
