# Generated by Django 3.2.3 on 2021-07-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0065_channel_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='namews',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
