# Generated by Django 3.2.3 on 2021-07-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0067_alter_channel_namews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='namews',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
