# Generated by Django 3.2.3 on 2021-07-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0068_alter_channel_namews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='namews',
            field=models.CharField(max_length=255),
        ),
    ]
