# Generated by Django 3.2.3 on 2021-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0069_alter_channel_namews'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='id2',
            field=models.TextField(default=''),
        ),
    ]
