# Generated by Django 3.2.3 on 2021-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0071_channel_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id2',
            field=models.TextField(default='', unique=True),
        ),
    ]
