# Generated by Django 3.2.3 on 2021-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0075_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='folder',
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ManyToManyField(blank=True, default=None, to='channel.folder'),
        ),
    ]
