# Generated by Django 3.2.3 on 2021-07-29 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0076_auto_20210728_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.video')),
            ],
        ),
    ]
