# Generated by Django 3.2.3 on 2021-07-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0080_auto_20210730_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolike',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
