# Generated by Django 3.2.3 on 2021-07-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0081_videolike_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolike',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
