# Generated by Django 3.2.3 on 2021-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0082_videolike_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoview',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoview',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
