# Generated by Django 3.2.3 on 2021-07-30 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0084_auto_20210730_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolike',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videoview',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
