# Generated by Django 3.2.3 on 2021-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0086_dataanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='duration',
            field=models.CharField(default=7, max_length=50),
        ),
    ]
