# Generated by Django 3.2.3 on 2021-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0091_comment_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100),
        ),
    ]
