# Generated by Django 3.2.6 on 2021-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0092_comment_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('video', models.ManyToManyField(blank=True, default=None, to='channel.video')),
            ],
        ),
    ]
